### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Taki21** [BoxOfDevs/BedWars#2]
## FEATURES VB.1:

- [ ] Bed Colors

- [ ] Team(s) Colors

- [ ] Customizable Config and Plugin

- [ ] Up To <configurable per arena> players a Match

- [ ] Secret Chests
- [ ] Choice for minimum and maximum amount of players: less than or same as the amount <configurable per arena>

- [ ] Automatic Generators just with 1 command

- [ ] Use Signs For Game Join

- [ ] BedKits

- [ ] Customize in game aspects (Health, Hunger, Damage etc...)

**Comment by HimbeersaftLP** [comment]
Wouldn't unlimited players with a selectable max per game and per team better?

**Comment by Taki21** [comment]
planning to d o that in a different version lol
im trying to make a simple but kewl release :p

**Comment by Taki21** [comment]
well it cant be unlimited since there are only like 10 or 20 colors im minecraft but peeps per team can be unilimited

**Comment by HimbeersaftLP** [comment]
But the doesn't explain the player limit, also, just let the users choose the color per team, they will find out that there aren't unlimited colors at some time sooner or later...

**Comment by Thunder33345** [comment]
i think colour can be unlimited
by doing this
colour1 colour2 thus you now have more then you need, or you can use 3 colour digit too
I HOPE this project will be flexible like begin able to run multiple matches etc
You should also consider using the projects panel

**Comment by HimbeersaftLP** [comment]
> I HOPE this project will be flexible like begin able to run multiple matches etc

This plugin will be arraytastic 😛

**Comment by Taki21** [comment]
@Thunder33345 minecraft colors

**Comment by Thunder33345** [comment]
yes you can do like [colour1][colour2]

which would results in BLACK GREEN team as ex

**Comment by HimbeersaftLP** [comment]
What about not using colors but custom teams, a file like teams.yml which lets you set the teams Name (e.g. §bBlue Team), the teams primary color (e.g. AQUA), the teams, the teams leather armor color scheme (e.g. Green Chestplate and Blue helmet...)

Then another file, arenas.yml which let's you define which teams are for which arena and how many players can be in there. Also the bed and generator positions are saved in this file

**Comment by Taki21** [comment]
but isnt 15 teams max enough?
@Thunder33345 that will make the players confused in gameplay

**Comment by Thunder33345** [comment]
i dont think so there's ton of mega UHCs that basically run off duo/trio colours and it works fine i dont see how that can be confusing for players, but it may be confusing on the programmer's end

i personally go against the idea of since XYZ limit would rarely be meet lets not make it support that, my problem with that is it promotes lazy/bad coding, like

> meh dont bother no one will ever need it so i dont need to implement it

i get it that we all like to cut edges but while you are at it you might as well fix it, or you can never fix it ever again(without a painful rewrite or major update)

**Comment by HimbeersaftLP** [comment]
> but isnt 15 teams max enough?
@Thunder33345 that will make the players confused in gameplay

Make it like in my message above and let it default to the 15 teams, hardcoding is a really really bad idea

**Comment by Thunder33345** [comment]
yes that's what i meant, dont hardcode a limit but allow owners to set their own limit

**Comment by dries-c** [comment]
use this plugin and make a rewrite https://github.com/NL-4-DEVS/Eggwars

**Comment by HimbeersaftLP** [comment]
But we want to do it from scratch...

**Comment by dries-c** [comment]
ok

Op 12-apr.-2017 10:54 schreef "HimbeersaftLP" <notifications@github.com>:

**Comment by Erkam246** [comment]
@Taki21 can i commit to help?

**Comment by Taki21** [comment]
@erkam2002 sure :D

**Comment by Taki21** [comment]
guyz im back and ima continue dis plugin, i was learning java 4 some reason so dont blame meh xD

**Comment by AvgZing** [comment]
Okay...

**Comment by Vaults1** [comment]
@Taki21 don't you need a plugin.yml?

**Comment by Taki21** [comment]
Will do dat l8r or if someone wants to do it now xd

**Comment by SyntaxDragon** [comment]
Too lazy you can change stuff cause I noticed no permisons and probs missing main
---
name: Bedwars
author: BoxOfDevs Team
version: 1.0.0
main: BoxOfDevs/BedWars/Taki21
api: [2.0.0, 2.1.0, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6]
commands: 
  bw:
    description: "bedwars command"
    usage: "/bw add <Colour>"
---

**Comment by SyntaxDragon** [comment]
also for customisation of aspects why not use a chest gui with interaction of changing gamemode types

**Comment by dries-c** [comment]
RIP

**Comment by Taki21** [comment]
rip ikr

**Comment by Taki21** [comment]
how to php?

**Comment by AvgZing** [comment]
lol

**Comment by Taki21** [comment]
does anyone have time machine? I need it real bad, dont feel like to relearn...

**Comment by AvgZing** [comment]
Yeah, I do! I Can't give it to you, sorry

**Comment by Taki21** [comment]
Crunchy takis coming your way

**Comment by AvgZing** [comment]
Thanks!
